#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as super user" 1>&2
   exit 1
fi

echo "Extract the installed files list"
python setup.py install --record unistall-files.txt >/dev/null
echo "Delete the installed files"
cat unistall-files.txt | xargs rm -rf
echo "Delete temporal uninstall process files."
rm unistall-files.txt
echo "Check that the odooscaffold was deleted"
whereis odooscaffold >/dev/null

#echo $?
if [[ $? == 1 ]]; then
    echo "Error: the odooscaffold was not uninstalled."
fi
